canvas=document.getElementById("my_canvas");
ctx=canvas.getContext("2d");
colour="blue";
ctx.beginPath();
ctx.strokeStyle=colour;
ctx.lineWidth= 4;
ctx.arc(200,200,40,0,2*Math.PI);
ctx.stroke();
ctx=canvas.getContext("2d");
colour="black";
ctx.beginPath();
ctx.strokeStyle=colour;
ctx.lineWidth= 4;
ctx.arc(300,200,40,0,2*Math.PI);
ctx.stroke();
ctx=canvas.getContext("2d");
colour="red";
ctx.beginPath();
ctx.strokeStyle=colour;
ctx.lineWidth= 4;
ctx.arc(400,200,40,0,2*Math.PI);
ctx.stroke();
ctx=canvas.getContext("2d");
colour="yellow";
ctx.beginPath();
ctx.strokeStyle=colour;
ctx.lineWidth= 4;
ctx.arc(250,250,40,0,2*Math.PI);
ctx.stroke();
ctx=canvas.getContext("2d");
colour="green";
ctx.beginPath();
ctx.strokeStyle=colour;
ctx.lineWidth= 4;
ctx.arc(350,250,40,0,2*Math.PI);
ctx.stroke();